name: 'Notion Pages'
description: 'Generate markdown files in _posts folder from Notion pages.'
author: 'Bendy Zhang'
inputs:
  notionToken:
    required: true
    description: 'Notion access token'
  rootPageId:
    required: true
    description: 'root page id'
  outputDir:
    required: false
    description: 'output folder'
    default: './_posts/'

runs:
  using: 'node16'
  main: 'dist/index.js'
